<a href="https://colab.research.google.com/github/Nilswonderland/Portfolio/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [2]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [ ]:
my_list=[5,10,15,20,25]

my_array = np.array(my_list)
my_array

array([ 5, 10, 15, 20, 25])

In [ ]:
#answer

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [ ]:
zero_array = np.zeros([5,5])
zero_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#answer

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [ ]:
ones_array = np.ones([4,4], dtype = "int")
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#answer

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [ ]:
sevens_array = np.ones([4,4], dtype = "int")*7
sevens_array

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
#answer

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [ ]:
np.full([4,4], 7 , dtype = "int")

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
#answer

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [4]:
numbers = np.arange(2,17,2)
numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
#answer

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [7]:
number_list = np.arange(0,25).reshape(5,5)
number_list

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
#answer

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [9]:
np.linspace(0,24,25, dtype = "int").reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
#answer

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [ ]:
#answer

array([0.76358107, 0.87803301, 0.80945923, 0.58642508, 0.32335644])

In [11]:
random_numbers = np.random.rand(5)
random_numbers

array([0.87943142, 0.37556373, 0.60539518, 0.81248453, 0.10101906])

#### 11. Create random normal distributed 5x5 array

In [ ]:
np.random.randn(5,5)

array([[ 1.69213492, -1.41916041,  0.21782187, -0.46795481, -0.32285581],
       [ 0.58925155, -0.90541001,  0.02379443, -0.22511484,  0.61566195],
       [-0.58676499, -0.56440388,  0.14506732, -0.56006078, -1.44345691],
       [ 1.48214535, -1.35152687, -0.10862782,  3.31195388,  0.57962834],
       [-0.27668729,  0.11587623,  0.94993712, -0.07688491,  0.57282527]])

In [ ]:
#answer

array([[-1.88145979, -0.33694765,  1.00329733, -0.78862807, -0.95450456],
       [ 1.3872682 , -1.05838181,  1.38137969, -0.58068211, -1.45203318],
       [-0.1202232 , -0.02930381,  0.46451676, -0.62666937, -0.14675805],
       [-0.30564453,  1.83376643,  0.82751037, -0.63556272,  1.44643513],
       [ 0.63463514, -0.67219484, -0.17806175,  0.81716206, -1.14449609]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [ ]:
np.random.randint(20,50, size = [3,4])

array([[47, 41, 27, 22],
       [25, 46, 22, 34],
       [28, 23, 42, 32]])

In [ ]:
#answer

array([[41, 44, 49, 32],
       [43, 20, 20, 49],
       [26, 39, 39, 44]])

#### 13. Reshape the array below with shape 6x8

In [12]:
ranarr = np.random.randint(0, 60, 48)

In [13]:
ranarr

array([35, 46, 41, 50, 20, 50, 13, 24,  5, 20,  7,  3,  9, 43, 40, 14, 31,
       25, 22, 16, 49, 53,  9, 40, 57, 18, 38, 12,  4, 58, 51,  2, 50, 56,
       21, 12, 20,  3, 14,  0,  1, 46, 55, 23,  0, 22, 21, 56])

In [14]:
ranarr.reshape(6,8)

array([[35, 46, 41, 50, 20, 50, 13, 24],
       [ 5, 20,  7,  3,  9, 43, 40, 14],
       [31, 25, 22, 16, 49, 53,  9, 40],
       [57, 18, 38, 12,  4, 58, 51,  2],
       [50, 56, 21, 12, 20,  3, 14,  0],
       [ 1, 46, 55, 23,  0, 22, 21, 56]])

In [ ]:
#answer

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [ ]:
ranarr.reshape(-1,8)

array([[15, 36, 31, 47, 16, 44, 43, 40],
       [18, 50, 30,  5, 11, 38, 27, 38],
       [21, 58,  1, 26, 19,  6, 56,  0],
       [54, 52, 26, 11, 51, 17, 24, 49],
       [34, 31, 46, 41, 38, 55, 31, 40],
       [21,  4, 11, 17, 45, 35, 55, 26]])

In [15]:
#reshape with -1
#answer


## Numpy Indexing and Selection


In [ ]:
#Create array below
mat=
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [23]:
mat = np.arange(1,17).reshape([4,4])
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [24]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
mat[1:3 , 1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

array([ 1,  5,  9, 13])

In [ ]:
mat[0:, 0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [32]:
row = mat[1,::2]
row

array([5, 7])

In [ ]:
#answer

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [73]:
mat[:,2] = 77
mat


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
#answer
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [38]:
mat[[1,3],[0,1]]

array([ 5, 14])

In [ ]:
#answer

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [ ]:
#answer

array([[ 5, 77],
       [13, 77]])

In [39]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [47]:
mat[1::2,0::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [ ]:
#answer

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [59]:
below_10 = mat[mat<10]
below_10

array([1, 2, 4, 5, 6, 8, 9])

In [ ]:
#answer

array([1, 2, 4, 5, 6, 8, 9])

In [ ]:
#answer

array([77, 77, 77, 13, 14, 77, 16])

In [60]:
above_12 = mat[mat>12]
above_12

array([77, 77, 77, 13, 14, 77, 16])

In [61]:
sum_1 = below_10 + above_12
sum_1

array([78, 79, 81, 18, 20, 85, 25])

In [ ]:
#answer

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [63]:
standard_deviation = np.std(sum_1)
standard_deviation

29.700546274093877

In [ ]:
#answer

29.700546274093877

#### 22. Get the sum of second column from array above

In [ ]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [65]:
second_column = sum(mat[:,1])
second_column

32

In [ ]:
#answer

32

#### 23. Get the median,mean and std of 3rd row from array above

In [ ]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [78]:
mat_former = np.array([[ 1,  2,  3,  4], 
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]]) # since we change mat function, I defined again.
mat_former

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [79]:
third_row = mat_former[2] 
third_row


array([ 9, 10, 11, 12])

In [80]:
np.median(third_row)

10.5

In [ ]:
#median


10.5

In [81]:
np.mean(third_row)

10.5

In [ ]:
#mean


10.5

In [82]:
np.std(third_row)

1.118033988749895

In [ ]:
#std


1.118033988749895

# Pandas Section

In [83]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [101]:
salary=pd.read_csv('Salaries.csv')

In [102]:
salary

Id       EmployeeName  ...         Agency  Status
0            1     NATHANIEL FORD  ...  San Francisco     NaN
1            2       GARY JIMENEZ  ...  San Francisco     NaN
2            3     ALBERT PARDINI  ...  San Francisco     NaN
3            4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4            5    PATRICK GARDNER  ...  San Francisco     NaN
...        ...                ...  ...            ...     ...
148649  148650      Roy I Tillery  ...  San Francisco     NaN
148650  148651       Not provided  ...  San Francisco     NaN
148651  148652       Not provided  ...  San Francisco     NaN
148652  148653       Not provided  ...  San Francisco     NaN
148653  148654          Joe Lopez  ...  San Francisco     NaN

[148654 rows x 13 columns]

In [104]:
first_five = salary.head()
first_five

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [ ]:
#dfinfo

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [106]:
salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [107]:
salary.describe()

Id        BasePay  ...  Notes  Status
count  148654.000000  148045.000000  ...    0.0     0.0
mean    74327.500000   66325.448841  ...    NaN     NaN
std     42912.857795   42764.635495  ...    NaN     NaN
min         1.000000    -166.010000  ...    NaN     NaN
25%     37164.250000   33588.200000  ...    NaN     NaN
50%     74327.500000   65007.450000  ...    NaN     NaN
75%    111490.750000   94691.050000  ...    NaN     NaN
max    148654.000000  319275.010000  ...    NaN     NaN

[8 rows x 10 columns]

**How many different year value are there**

In [ ]:
#Answer

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [108]:
salary.Year.value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [ ]:
#max


567595.43

In [109]:
salary.TotalPay.max()

567595.43

In [ ]:
#avg


74768.321971703

In [110]:
salary.TotalPay.mean()

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [ ]:
#Answer

69489

In [112]:
len(salary[salary.TotalPay > salary.TotalPay.mean()])

69489

**How much does ALBERT PARDINI make (including benefits)?**

2    335279.91
Name: TotalPayBenefits, dtype: float64

In [113]:
salary[salary["EmployeeName"] == "ALBERT PARDINI"]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

148653    Joe Lopez
Name: EmployeeName, dtype: object

In [115]:
salary[salary.TotalPayBenefits == salary.TotalPayBenefits.min()]["EmployeeName"]

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

In [116]:
salary["JobTitle"].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

In [117]:
salary.JobTitle.value_counts().tail(3)

SUPERVISING PARTS STOREKEEPER     1
DISABILITY ACCESS COORDINATOR     1
COURT ADMINISTRATIVE SECRETARY    1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

20366

In [127]:
salary[(salary.TotalPayBenefits > salary.TotalPayBenefits.mean()) & (salary.Year == 2012)]["EmployeeName"].count()

20366

**How many people have the word Manager in their job title?**

In [ ]:
#use apply function here


4110

In [140]:
def manager_function(x):
  if "manager" in x.lower() :
    return True
  else:
    return False



In [141]:
len(salary[salary.JobTitle.apply(lambda x: manager_function(x))])

4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [142]:
sal.head()

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [143]:
salary_new= salary.iloc[:,[0, 1, 2, 7, 8]]
salary_new

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0            1     NATHANIEL FORD  ...  567595.43         567595.43
1            2       GARY JIMENEZ  ...  538909.28         538909.28
2            3     ALBERT PARDINI  ...  335279.91         335279.91
3            4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4            5    PATRICK GARDNER  ...  326373.19         326373.19
...        ...                ...  ...        ...               ...
148649  148650      Roy I Tillery  ...       0.00              0.00
148650  148651       Not provided  ...       0.00              0.00
148651  148652       Not provided  ...       0.00              0.00
148652  148653       Not provided  ...       0.00              0.00
148653  148654          Joe Lopez  ...    -618.13           -618.13

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [146]:
salary_new= salary_new.loc[:,"EmployeeName":"TotalPayBenefits"]
salary_new

EmployeeName  ... TotalPayBenefits
0          NATHANIEL FORD  ...        567595.43
1            GARY JIMENEZ  ...        538909.28
2          ALBERT PARDINI  ...        335279.91
3       CHRISTOPHER CHONG  ...        332343.61
4         PATRICK GARDNER  ...        326373.19
...                   ...  ...              ...
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00
148653          Joe Lopez  ...          -618.13

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object

In [151]:
salary[((salary.TotalPayBenefits > salary.TotalPayBenefits.min()) & (salary.TotalPayBenefits < salary.TotalPayBenefits.mean()))]["EmployeeName"]

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object